all:
	cd phddns-2.0.6.32828; ./configure --host=i386-linux --target=arm-linux--build=arm-linux CXX=arm-none-linux-gnueabi-c++ CC=arm-none-linux-gnueabi-gcc LD=arm-none-linux-gnueabi-ld
	cd phddns-2.0.6.32828; make
clean:
	cd phddns-2.0.6.32828; make distclean
